baseURL = "/"
languageCode = "en-us"
title = "not quite an expert"
enableEmoji=true

[params]
    author = "Jason Jin"
    description = "not quite an expert in anything, interested in many things"
    avatar = "avatar.jpg"

    [[params.social]]
        icon = "brand-github"
        name = "github"
        url = "https://github.com/jgjin"
    [[params.social]]
        icon = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/jason-jin1"

[params.style]
    darkestColor = "#4b1a4f"
    darkColor = "#211d27"
    lightColor = "#fcf8fd"
    lightestColor = "#ffffff"
    primaryColor = "#c34bcc"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
[[module.imports]]
    path = "github.com/vaga/hugo-theme-m10c"
